### ISSUE TITLE
Introducing starter in start.spring.io

### ISSUE THREAD

**Issue by rakk** [akkinoc/orika-spring-boot-starter#8]
Hi,

I created a pull request on https://github.com/spring-io/initializr/pull/687
but the pull request has been declined because of missing support for Spring-Boot 2.0 and general lack of active development.

I see that the support to Spring-Boot 2.x has been added.
What do you think about re-asking to add this pull request?

**Comment by akkinoc** [comment]
Sorry for the late reply.
Thank you for introducing starter to start.spring.io!

If the re-requested pull request will be merged, I will be happy.
However, it is difficult to actively and continuously develop this project,
because this project is being developed by an individual and using my limited time.

Thanks.

**Comment by akkinoc** [comment]
This issue is not active, so I will close it.
If you still have problems, please open a new issue.
